export const PRELOADED_SOPS = [
  {
    id: "SOP-INV-001",
    title: "Inventory Management Procedure",
    purpose: "To define the procedure for receiving, storing, and issuing electronic components to ensure reel-level traceability.",
    scope: "Applies to all incoming materials, warehouse management, and production issue.",
    procedure: `
      1. GRN Generation: All materials must be logged into the QMS with a unique GRN number upon physical receipt.
      2. IQC Blockage: Materials remain in QUARANTINE status until Incoming Quality Control (IQC) passes the batch.
      3. Traceability: Each reel must be tagged with a unique QR code generated by the system before storage.
      4. Storage: Reels must be stored in designated Bins/Racks. Humidity-sensitive components must be stored in dry cabinets according to MSL ratings.
      5. FIFO/FEFO: Oldest lots and parts nearest to expiry must be issued first.
    `
  },
  {
    id: "SOP-IQC-002",
    title: "IQC Inspection Standards",
    purpose: "Ensure all incoming parts meet required specifications before entering production inventory.",
    procedure: `
      1. Sampling: Inspect 5 random samples per lot (or AQL standard).
      2. Measurement: Use calibrated LCR meters for passives. Document measured values in the QMS.
      3. Visual Check: Verify MSL packaging integrity, pin straightness, and absence of oxidation.
      4. Outcome:
         - PASS: System updates reel status to ACCEPTED.
         - FAIL: System generates Non-Conformance Report (NCR) and material is sent to MRB (Material Review Board).
    `
  },
  {
    id: "SOP-NCR-003",
    title: "Non-Conformance & CAPA Management",
    purpose: "Identify, control, and prevent the recurrence of non-conforming products.",
    procedure: `
      1. Raise NCR: Any operator or inspector finding a defect must log an NCR detailing Part No, Reel ID, and defect type.
      2. Quarantine: The affected reel is immediately locked systematically from being issued to production.
      3. Root Cause Analysis: The Quality team investigates the issue using 5-Whys or Ishikawa.
      4. CAPA: A Corrective and Preventive Action plan is documented and assigned.
      5. Closure: CAPA effectiveness is verified before the NCR is closed in the system by the Quality Head.
    `
  }
];

export const FORMAT_TEMPLATES = [
  {
    id: "FMT-GRN-01",
    name: "Goods Receipt Note Format",
    fields: ["GRN Number", "Supplier", "Invoice Ref", "Date Received", "Receiver Name", "Visual Condition"]
  },
  {
    id: "FMT-IQC-01",
    name: "IQC Inspection Report",
    fields: ["GRN Ref", "Part Number", "Lot Number", "Sample Size", "Visual Result", "Electrical Result", "Inspector Sign"]
  },
  {
    id: "FMT-NCR-01",
    name: "Non-Conformance Report",
    fields: ["NCR Number", "Date Raised", "Reel/Lot ID", "Defect Description", "Containment Action", "Root Cause", "CAPA Ref"]
  }
];
